# Generated by Django 3.2 on 2023-06-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique subscription',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='follower not following',
        ),
    ]
